### ISSUE TITLE
发现个问题

### ISSUE THREAD

**Issue by SoulArsenic** [dsxNiubility/SXWaveAnimate#3]
~~内存方面好像有问题， tableViewController 被销毁的时候 有内存始终在被占用着~~

然后就是一个建议， 感觉动画的实现用CAAnimation 会更流畅些 ，我分支尝试了一下，感觉上衔接会比拼接的强点。

还有一个就是那个波浪的资源图， 最好是左右有部分能够重叠， 这样过渡重复动画的时候 就不会有跳跃感了

**Comment by dsxNiubility** [comment]
感谢你的建议， 现在只用到了基础动画就没动用core Animation了，后面可能会更改外围的转圈，那时候能能需要再加入定时器。  关于内存不能释放 我试了下tableviewController销毁时delloc方法会调用啊（你看看你用的是不是最新的代码）。  图片的话这个图只能这样了，以后换图的话会吸取你的建议 左右有重合

**Comment by SoulArsenic** [comment]
确实会被调用，  但是运行时存在的内存貌似不对，刚启动时的内存是17左右， 推出tableviewController 后上升到27 ， 返回后内存并没有下降，我也没找到是哪的问题， 所以问问你。
![image](https://cloud.githubusercontent.com/assets/6848970/7953871/949b81ac-09fc-11e5-8be0-a8dcdc9b0d5e.png)

外围旋转和波浪的我试着改了一下， 我不知道怎么提交修改。感觉应该会有参照作用
[这是我的实现](https://github.com/LengBinBin/SXWaveAnimate/blob/master/SXWaveAnimate/SXWaveAnimate/Classes/WaveAnimate/SXWaveCell.m)

**Comment by SoulArsenic** [comment]
内存那个好像不是问题。。。 是storyboard创建后的对象会被系统托管， 不进入回收。

**Comment by dsxNiubility** [comment]
恩看了，你代码在无限播放的时候，隔段时间波纹会跳动一下，换个图片这个问题可以解决的，后续我会加个开关可以控制播放一次还是无限播放，会借鉴你的代码。

**Comment by SoulArsenic** [comment]
got that .
